swagger: '2.0'
info:
  version: 1.0.0
  title: petApi
  description: Sample API for Getty
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: PetManagement
    description: Example endpoint for Pet Management
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  PetModel:
    type: object
    title: PetModel
    required:
      - name
      - description
      - age
    properties:
      _id:
        type: string
      name:
        type: string
        example: rufus
      description:
        type: string
        example: big dog
      age:
        type: number
        example: 1
  PetModelDTO:
    type: object
    title: PetModelDTO
    required:
      - name
      - description
      - age
      - _id
    properties:
      _id:
        type: string
      name:
        type: string
        example: rufus
      description:
        type: string
        example: big dog
      age:
        type: number
        example: 1

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: '#/definitions/ExampleBody'
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /pet:
    post:
      tags:
        - PetManagement
      description: Create a new Pet
      parameters:
        - name: PetModel
          in: body
          description: a pet object
          required: true
          schema:
            $ref: '#/definitions/PetModel'
      responses:
        200:
          description: Returns all examples

  /pet/{id}:
    get:
      tags:
        - PetManagement
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        200:
          description: Return a pet with the specified id
        404:
          description: Pet not found
  /pet/delete/{id}:
    delete:
      tags:
        - PetManagement
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the pet to remove
          type: string
      responses:
        200:
          description: Return a pet with removed
        404:
          description: Pet not found
  /pet/put:
    put:
      tags:
        - PetManagement
      parameters:
        - name: PetModelDTO
          in: body
          description: a pet object
          required: true
          schema:
            $ref: '#/definitions/PetModelDTO'
      responses:
        200:
          description: Return the updated pet
        500:
          description: An error ocurred while processing the update

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
